import type { Metadata } from "next";
import "./global.css";
import { Poppins } from "next/font/google";
import Header from "./Components/header/page";
const poppins = Poppins({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Header />
      <body className={`${poppins}`}>{children}</body>
    </html>
  );
}
