import type { Metadata } from "next";
import "./global.module.sass";
import { Poppins } from "next/font/google";
// import Header from "./Components/header/page";
import Login from "./login/page";
const poppins = Poppins({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="html">
      <Login />
      <body className={`${poppins}`}>{children}</body>
    </html>
  );
}
